import { title } from "process";
import "./globals.css";
import {Inter} from "next/font/google";
const inter  =Inter ({subsets: ["latin"]});
export const metadata ={
  title: "crud | Nextja",
  description: "Generated by create next app",
}
export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container-flued mt-4">
          {children}
        </div>
      </body>
    </html>
  )
};